---
name: "Template"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.1.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Automatically generate M3U8 playlist for your media"
description: >
  This plugins will help generates an URL that can be used for media playback
  It utilize Jellyfin API key to help access the API route.
category: "General"
owner: "noaione"
artifacts:
- "N4O.Plugin.PlaylistGen.dll"
changelog: >
  - First version, should be similar to the original script
  - Route are now changed to just /PlaylistGen/Items/{itemId} for every thing.
  - There's /PlaylistGen/ClientScript route for jellyfin-web that can be used to inject `Copy as Playlist URL` button
